### ISSUE TITLE
Relation between UK parliament ontologies and ELI-DL

### ISSUE THREAD

**Issue by tfrancart** [ukparliament/ontologies#29]
ELI-DL is at https://joinup.ec.europa.eu/release/eli-dl/draft1. It is a generic event-based model to describe draft legislation processes, in the context of the [ELI european initiative](https://eur-lex.europa.eu/eli-register/about.html). It includes generic classes such as **LegalActivity**, **LegislativeProject**, **LegalDraftWork**, etc. It extends FRBRoo. Looks similar to Procedure and Step in your ontologies. As ELI-DL is generic, it is less precise than your ontologies; it is also made from the point of view of Official Journals that publish information about draft legislation, not from the point of view of parliaments themselves.
There is no real issue or question here, I am opening this ticket to make sure you are aware of the initiative, and maybe to followup here with some comments.

Here is a tiny example diagram for an Irish bill in ELI-DL.

![Capture](https://user-images.githubusercontent.com/2728945/74728257-b10d9d00-5242-11ea-8536-6383c67df109.PNG)

**Comment by fantasticlife** [comment]
Hi Thomas, It looks like we need to do something to bind our BusinessItem class:
https://ukparliament.github.io/ontologies/procedure/procedure-ontology.html#d4e248
to your LegalActivity class, probably via our interface classes:
https://ukparliament.github.io/ontologies/interface/interface.html
But - some of our procedures will not be tied to legal draft works. Some of them may be purely internal parliamentary procedure with no connection to legal texts.
Probably needs a little more thought on our side.

**Comment by fantasticlife** [comment]
Hi Thomas, We've taken another look at this and can't see how we'd map our models to yours. Our procedure model:
https://ukparliament.github.io/ontologies/procedure/procedure-ontology.html
is intended to as a general process flow model for parliamentary procedure. Some of which may pertain to legislation, some of which will not.
At first glance it appears we should look to map our WorkPackage to the ELI LegislativeProject and our BusinessItem to the ELI LegalActivity. But not all our work packages pertain to legal matters and not all our business items are related to legislation. A more generic level of project and activity might be useful here. Is there a better place to have this conversation?

**Comment by tfrancart** [comment]
Hello - Thanks for the answer ! ELI-DL is not made as a generic parliament ontology - like what you are doing - but is only interested in draft legislations, to the extent where these draft legislations are disseminated through public portals.
Probably ELI-DL could be seen as a dissemination ontology populated by your internal specific ontology, only when things get published on a website.
