### ISSUE TITLE
Filter collection resources not search pages

### ISSUE THREAD

**Issue by nickshanks** [ukparliament/ontologies#8]
You have URLs like `/contact-points/lookup?source=:source&id=:id`
These would be better expressed as filters on the /contact-points collection resource, i.e. remove `/lookup` leaving just `/contact-points?source=:source&id=:id`

Even if you need a search form as a separate resource from the collection list, the result of using the form should take you to the filtered collection.

**Comment by fantasticlife** [comment]
I'm afraid the beta website is considered deprecated.
